apiVersion: v1
kind: Pod
metadata:   
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app


spec:
  containers:
    - name: worker-app
      image:  kodekloud/examplevotingapp_worker:v2
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
        requests:
          cpu: "0.1"
          memory: "256Mi"